site_name: Made by YZJ
site_description: a personal blog made by YZJ
repo_url: https://github.com/Episd/Episd.github.io.git

nav:
  - Introduction:
    - About YZJ: index.md
  - Notes:
    - Introduction: Notes.md
    - JavaEE:
      - MyBatis: Notes\JavaEE\MyBatis\MyBatis.md

theme:
  name: material
  font:
    text: Merriweather Sans
    code: Fira Code
  icon:
    logo: fontawesome/solid/y
  palette: 
    # Dark Mode
    - scheme: slate       # 主题配色
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black      # 顶部主要配色
      accent: blue        # 改变强调色
    
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Light mode
      primary: white
      accent: deep orange
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.indexes
    - content.code.copy

markdown_extensions:
  - attr_list
  # 可以使用emoji
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # 允许使用网格
  - md_in_html
  # 格式
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  # 表格
  - tables
  # 代码语法高亮
  - pymdownx.highlight:
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
