site_name: Made by YZJ
site_description: a personal blog made by YZJ
repo_url: https://github.com/Episd/Episd.github.io.git

nav:
  - Introduction:
    - About YZJ: index.md
  - Notes:
    - Introduction: Notes.md
    - JavaEE:
      - MyBatis: 
        - MyBatis核心对象: Notes/JavaEE/MyBatis/MyBatisCoreObject/MyBatisCoreObject.md
        - MyBatis核心配置文件: Notes/JavaEE/MyBatis/MyBatisCoreConfig/MyBatisCoreConfig.md
  - DevelopmentDiary:
    - Introduction: DevelopmentDiary.md
    - Mkdocs个人博客搭建: 
      - 环境搭建: DevelopmentDiary/MkdocsBlog/EnvironmentBuild/EnvironmentBuild.md
      - 学习&开发日志: DevelopmentDiary/MkdocsBlog/Study&Development/Study&Development.md










theme:
  name: material
  font:
    text: Merriweather Sans
    code: Fira Code
  icon:
    logo: fontawesome/solid/y
  palette: 
    # Dark Mode
    - scheme: slate       # 主题配色
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black      # 顶部主要配色
      accent: blue        # 改变强调色
    
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Light mode
      primary: white
      accent: deep orange
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.indexes
    - content.code.copy
    - content.code.select
    - content.code.annotate

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
        custom_checkbox: true
        clickable_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
        generic: true
  - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
        alternate_style: true
      # 可以使用emoji
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  