site_name: Made by YZJ
site_url: https://mydomain.org/mysite
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Fira Code
  icon:
    logo: fontawesome/solid/y
  palette: 
    # Dark Mode
    - scheme: slate       # 主题配色
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black      # 顶部主要配色
      accent: blue        # 改变强调色
    
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Light mode
      primary: white
      accent: deep orange
  
markdown_extensions:
- attr_list
# 可以使用emoji
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
# 允许使用网格
- md_in_html
# 格式
- pymdownx.critic
- pymdownx.caret
- pymdownx.keys
- pymdownx.mark
- pymdownx.tilde
# 表格
- tables